stages:
    - deploy

# ---

deploy:image:
    before_script:
        - 'apk add --no-cache --no-progress ca-certificates curl'
    image:
        entrypoint: ['']
        name: alpine:latest
    only:
        - master
    script:
        - 'curl --request POST "https://cloud.docker.com/api/build/v1/source/60eca429-eb40-4a78-9d23-fa6dfef29486/trigger/${DOCKER_CLOUD_TOKEN}/call/"'
    stage: deploy
